#!/bin/bash
# Trim the Firecracker CI 6.1 guest config for boot speed.
# usage: trim.sh <config> [noacpi]
set -e
C="scripts/config --file $1"
# Boot-time costs seen in profiles
$C -e EXPERT
$C -d XFRM -d XFRM_USER -d INET_ESP -d INET_AH -d INET_IPCOMP -d NET_KEY -d CRYPTO_SEQIV -d CRYPTO_ECHAINIV -d CRYPTO_ECDH -d CRYPTO_DH -d KEY_DH_OPERATIONS -d CRYPTO_ECC -d CRYPTO_RNG_DEFAULT
$C -d CRYPTO_JITTERENTROPY -d CRYPTO_DRBG_MENU -d CRYPTO_DRBG -d CRYPTO_FIPS -e CRYPTO_MANAGER_DISABLE_TESTS
$C -d SPECULATION_MITIGATIONS -d PAGE_TABLE_ISOLATION -d RETPOLINE -d RETHUNK -d CPU_UNRET_ENTRY -d CPU_IBPB_ENTRY -d CPU_IBRS_ENTRY -d CPU_SRSO -d SLS -d MITIGATION_RFDS -d GDS_FORCE_MITIGATION
$C -d X86_PM_TIMER -d RANDOMIZE_BASE -d HZ_250 -e HZ_1000 --set-val HZ 1000
$C -d BLK_DEV_LOOP -d BLK_DEV_RAM -d MD -d BLK_DEV_DM -d SCSI -d ATA -d MQ_IOSCHED_DEADLINE -d MQ_IOSCHED_KYBER -d IOSCHED_BFQ
$C -d INPUT -d SERIO -d SERIO_I8042 -d KEYBOARD_ATKBD -d INPUT_KEYBOARD -d VT -d HID -d USB_SUPPORT -d SOUND -d DRM -d FB -d AGP
$C -d IPV6 -d NETFILTER -d BPFILTER -d BRIDGE -d NET_SCHED -d WIRELESS -d WLAN -d BT
$C -d NFS_FS -d NFSD -d SUNRPC -d XFS_FS -d BTRFS_FS -d SQUASHFS -d ISO9660_FS -d HUGETLBFS -d HUGETLB_PAGE
$C -d AUDIT -d SECURITY -d BPF_SYSCALL -d BPF_JIT -d KEXEC -d CRASH_DUMP -d HIBERNATION -d SUSPEND -d CPU_FREQ -d CPU_IDLE
$C -d NUMA -d DETECT_HUNG_TASK -d PTP_1588_CLOCK -d DEBUG_INFO -d DEBUG_INFO_DWARF5 -d DEBUG_INFO_DWARF4 -d DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT -d DEBUG_INFO_BTF -d KPROBES -d FTRACE -d DMI
$C -e IKCONFIG -e IKCONFIG_PROC -e VIRTIO_MMIO -e VIRTIO_MMIO_CMDLINE_DEVICES -e VIRTIO_BLK -e VIRTIO_NET -e EXT4_FS -e OVERLAY_FS -e DEVTMPFS -e BLK_DEV_INITRD -e FUSE_FS -e VIRTIO_FS -e VSOCKETS -e VIRTIO_VSOCKETS
if [ "$2" = "noacpi" ]; then
  $C -d ACPI -d PCI -d VMGENID -d PNP
fi
