#!/bin/bash
# Extra cuts on top of trim.sh for a single-application guest.
set -e
C="scripts/config --file $1"
$C -d KALLSYMS -d PERF_EVENTS -d PROFILING -d TASKSTATS -d IO_URING -d SYSVIPC -d POSIX_MQUEUE -d SWAP -d ZSWAP -d ZPOOL -d ZSMALLOC -d KSM
$C -d TRANSPARENT_HUGEPAGE -d COMPACTION -d MIGRATION -d SCHED_AUTOGROUP -d PROC_KCORE -d SLUB_DEBUG -d SLAB_FREELIST_RANDOM -d SHUFFLE_PAGE_ALLOCATOR -d SLAB_FREELIST_HARDENED
$C -d MPTCP -d INET_DIAG -d TLS -d XDP_SOCKETS -d NETLABEL -d DCB -d VLAN_8021Q -d BONDING -d TUN -d VETH -d MACVLAN -d IPVLAN -d VXLAN -d WIREGUARD -d NET_IPIP -d NET_IPGRE_DEMUX -d IP_ADVANCED_ROUTER -d IP_MULTICAST -d SYN_COOKIES -d NETDEVICES_MULTIQUEUE
$C -d FUSE_FS -d VIRTIO_FS -d OVERLAY_FS -d AUTOFS_FS -d QUOTA -d FANOTIFY -d DNOTIFY -d EXT4_FS_POSIX_ACL -d EXT4_FS_SECURITY -d FS_ENCRYPTION -d FS_VERITY -d MSDOS_FS -d VFAT_FS -d NLS
$C -d CGROUPS -d MEMCG -d BLK_CGROUP -d CPUSETS -d NAMESPACES -d USER_NS -d CHECKPOINT_RESTORE
$C -d VMGENID -d HW_RANDOM -d VIRTIO_BALLOON -d VIRTIO_MEM -d VIRTIO_INPUT -d VIRTIO_CONSOLE -d DEBUG_KERNEL -d MAGIC_SYSRQ -d DEBUG_FS -d STACKTRACE -d RD_GZIP -d RD_BZIP2 -d RD_LZMA -d RD_XZ -d RD_LZO -d RD_LZ4 -d RD_ZSTD
